### ISSUE TITLE
Version Number 

### ISSUE THREAD

**Issue by ctrlcmdshft** [ShayBox/Wooting-Profile-Switcher#10]
Can you add version number to the about section so we know the version we are running

**Comment by ShayBox** [comment]
I can add that, you can also check the binary for details
![image](https://github.com/ShayBox/Wooting-Profile-Switcher/assets/9505196/b300ded4-a8d8-4be0-9379-67d256280de0)

**Comment by ShayBox** [comment]
I added the version number in the latest update v2.1.2
