### ISSUE TITLE
New rule setup list has no scroll

### ISSUE THREAD

**Issue by SpeedBuff420** [ShayBox/Wooting-Profile-Switcher#11]
My game list is very long (2tb ssd worth of games) and cannot access the bottom of the new rule setup list without doing some gymnastics. i tried scrolling with my mouse and it does nothing. page up pade down also does nothing.

i can access it by minimising the window size and putting it at the bottom of my screen. Then pulling the list to the top of my screen past the Wooting Profile Switcher window.

![image](https://github.com/ShayBox/Wooting-Profile-Switcher/assets/145325540/2d1171ce-9464-40ad-b3bb-2b055ede8c1c)

please add a scrolling option or something i can press to access it easely. Thank you!

**Comment by ShayBox** [comment]
I added a scroll bar in the latest update v2.1.2
