### ISSUE TITLE
2.3.3 update results in program crash

### ISSUE THREAD

**Issue by YuumiPie** [ShayBox/Wooting-Profile-Switcher#16]
Running the wooting profile switcher on the newest version results in it appearing on taskbar for a few seconds before crashing

Info: 
1. Running on the msi download
2. Keyboard is the Wooting 60HE
3. Running on windows 10

Steps taken:
1. Added C:\Program Files\wooting-profile-switcher to firewall (same result)
2. Roll back version to 2.3.2 (works fine)

**Comment by ShayBox** [comment]
Try running the portable debug build in a terminal/PowerShell/command prompt window to see the logs

**Comment by ShayBox** [comment]
You may want to try deleting your config or clearing the devices section of it, there was some extra device info added which might be causing the crash.

**Comment by YuumiPie** [comment]
> You may want to try deleting your config or clearing the devices section of it, there was some extra device info added which might be causing the crash.

Ok so I think I followed the steps but the result is the same crash:

1. changed the device name in the config file to an empty string (no change of files)
2. removed the quotes in the config file of the device name (no change of files)
3. removed the config file (result in the creation of a new config file but with an empty device list)
4. launched wootility to try to update device list (no change in device list in config file)
5. fully removed all traces of the profile switcher (uninstall with msi and removed config file) (same result as 3)

I also have the ARM version that I forgot to say before, idk if it makes a difference. I'm not sure where to download a portable debug build (I ran the normal portable in cmd and powershell but no logs).

**Comment by ShayBox** [comment]
![Screenshot 2024-03-26-022058](https://github.com/ShayBox/Wooting-Profile-Switcher/assets/9505196/f47836f2-627b-456b-a02f-eea57600b271)

The portable version is a debug build, but if you get no output I'm not sure where to start to debug.
Make sure there's not a wooting-profile-switcher process running, no output usually means it found an instance running.

**Comment by YuumiPie** [comment]
> ![Screenshot 2024-03-26-022058](https://private-user-images.githubusercontent.com/9505196/316749820-f47836f2-627b-456b-a02f-eea57600b271.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzQ5MDcsIm5iZiI6MTcxMTQzNDYwNywicGF0aCI6Ii85NTA1MTk2LzMxNjc0OTgyMC1mNDc4MzZmMi02MjdiLTQ1NmItYTAyZi1lZWE1NzYwMGIyNzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMDYzMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDk5MWMzNzJiNmYxZmQwMDJmMTIwYmY0MDZkODYwODE5ZmQ2MjBiMDBiZTRjNWRjNDViZjhjNWJlMjkwMTM1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XZ2RVN0wYpGYwQKKbMj39Hv2XxfClzISoAAl1mY9uGw)
> 
> The portable version is a debug build, but if you get no output I'm not sure where to start to debug. Make sure there's not a wooting-profile-switcher process running, no output usually means it found an instance running.

ah I made a mistake I did "start wooting-profile-switcher_2.3.3_x64-portable.exe" instead of just "wooting-profile-switcher_2.3.3_x64-portable.exe" but this is the logs:

This is on a fresh portable download:
![image](https://github.com/ShayBox/Wooting-Profile-Switcher/assets/119447648/55856f4b-60e4-4984-b284-2e682eb67b37)

1. The first is after I downloaded the program before opening wootility
2. Second is I ran while wootility was open
3. Third is running the program again with wootility closed

**Comment by ShayBox** [comment]
What version of Wootility are you using?

In the Wootility dev tools (Ctrl + Shift + I) -> Application -> Local Storage -> file:// -> persist:root  
What are the version numbers and does the profiles section look similar in format to mine?

![image](https://github.com/ShayBox/Wooting-Profile-Switcher/assets/9505196/8849ff5c-a2ce-4726-bde3-d1e3058d54d4)

**Comment by YuumiPie** [comment]
![image](https://github.com/ShayBox/Wooting-Profile-Switcher/assets/119447648/408c0bf1-ec0a-499c-957b-72ad9fd8aa87)
I'm not sure if this is correct but this is a screenshot of my wootility.

**Comment by ShayBox** [comment]
It appears the RGB SDK couldn't find any connected devices, try re-plugging your keyboard(s)

Could you tell me what the name of your keyboard(s) are in device manager, and could you try switching between the different gamepad modes in Wootility to see if that changes the log output?

**Comment by YuumiPie** [comment]
I switched the usb port (no change) and this is the keyboard of my device manager with hidden devices shown

![image](https://github.com/ShayBox/Wooting-Profile-Switcher/assets/119447648/01b08e0d-e405-4507-86b9-531e557ff829)
after changing it to classic controller mode (first time)
![image](https://github.com/ShayBox/Wooting-Profile-Switcher/assets/119447648/8a684a4a-3c4d-42d6-95ab-a6b83658aaa9)
after adding xbox controller (first time)
![image](https://github.com/ShayBox/Wooting-Profile-Switcher/assets/119447648/0276b85c-bf64-4934-8952-23835173048f)

no change when running portable version in all steps (wootility closed)

**Comment by YuumiPie** [comment]
I previously had Wooting Analog SDK downloaded and uninstalled it to see if anything will change, but same error.

**Comment by YuumiPie** [comment]
I'm not sure if this is relevent but there was an event of multiple instances of the profile switcher in my windows quickbar (mini menu in the right) before rapidly closing.

**Comment by ShayBox** [comment]
Can you run the portable build of this pre-release https://github.com/ShayBox/Wooting-Profile-Switcher/releases/tag/2.3.4

**Comment by ShayBox** [comment]
Try this version https://github.com/ShayBox/Wooting-Profile-Switcher/releases/tag/2.3.4

**Comment by YuumiPie** [comment]
result:
![image](https://github.com/ShayBox/Wooting-Profile-Switcher/assets/119447648/da45c465-4621-47b0-b3b4-c5511abfdabf)

**Comment by ShayBox** [comment]
Okay I believe I figured out the issue, I thought product_id (48 in the Serial Buffer) was only 2 bytes long but it might be variable length with an end byte of 3 (possibly because 3 >>> 3 == 0), try this version

https://github.com/ShayBox/Wooting-Profile-Switcher/releases/tag/2.3.4

**Comment by YuumiPie** [comment]
Nice! Seems the issue is fixed with this version. The wooting is detected in the json file. Tested switching profiles with default/configs and worked perfectly.

Thanks!

Logs from cmd:
[output.txt](https://github.com/ShayBox/Wooting-Profile-Switcher/files/14757421/output.txt)
Some additional text not caught in the log:
![image](https://github.com/ShayBox/Wooting-Profile-Switcher/assets/119447648/0d730bc4-1893-485b-b36b-271e476c272b)

First logs seems to be compleatly normal, but idk if the second line in the bottom image is cause for concern, nontheless the issue seems solved.

**Comment by ShayBox** [comment]
I forgot to update the Tauri version number, a new release is building and will auto update when available.
