### ISSUE TITLE
App crashes when swapping rules outside of list

### ISSUE THREAD

**Issue by jkapi** [ShayBox/Wooting-Profile-Switcher#18]
When trying to move the top rule up or the bottom rule down the application crashes.

https://github.com/ShayBox/Wooting-Profile-Switcher/assets/16419568/45fed8ae-2dac-4180-92bf-1c85b88ed1ce

**Comment by ShayBox** [comment]
Try this pre-release https://github.com/ShayBox/Wooting-Profile-Switcher/releases/tag/2.3.6

**Comment by jkapi** [comment]
It works!

Although I do wonder if wrapping around is the best choice, maybe just keep it at the top or bottom if it's there already.

**Comment by jkapi** [comment]
Fixed in with 2d1c629
