### ISSUE TITLE
No full example for configuration

### ISSUE THREAD

**Issue by AaronEinbaer** [ShayBox/Wooting-Profile-Switcher#9]
I'm trying to get this to work with Counter-Strike.

I don't know if any of these configurations is correct:

    {
      "app_name": Counter-Strike: Global Offensive,
      "process_name": "csgo.exe",
      "process_path": C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive,
      "title": CSGO,
      "profile_index": 1
    }
    {
      "app_name": Counter-Strike: Global Offensive,
      "process_name": "csgo.exe",
      "process_path": C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe,
      "title": CSGO,
      "profile_index": 1
    }

I don't know which profile correlates to which profile_index. Or **if this just doesn't work right with the 60HE** (manual profile switching in the task tray is possible).

It would also be really nice if you could access the config folder through the task tray icon or if the software could detect the wooting profile names and would display them. You could add an profile_index table to the top of the config file that includes the Wooting profile name (for example Analog 1), and the assigned name / label.

**Comment by ShayBox** [comment]
The `profile_index` you set in each rule object corresponds with what profile will be activated when one of the variables in that rule object match the active window.

There are a few JSON syntax errors with your examples, you need to surround strings with double quotes and you need a comma between objects and variables.

```json
{
  "app_name": "Counter-Strike: Global Offensive",
  "process_name": "csgo.exe",
  "process_path": "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive",
  "title": "CSGO",
  "profile_index": 1
},
{
  "app_name": "Counter-Strike: Global Offensive",
  "process_name": "csgo.exe",
  "process_path": "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe",
  "title": "CSGO",
  "profile_index": 1
}
```
Using all 4 match variables isn't required, but it won't hurt to include multiple.

I am already working on v2 which adds a GUI to configure rules and settings, as-well-as adding support for reading the locally installed Wootility Chrome/Electron browser's local storage to access profile names and inactive profiles so you can upload inactive profiles in-memory (the keyboards only store 3 active profiles on flash) but the update will take some time,

**Comment by ShayBox** [comment]
I'm going to close this issue now that there's a built-in UI to edit rules. Please make sure to manually remove existing installations prior to installing Wooting Profile Switcher v2.

If you have any questions or need any help feel free to comment, open a new issue, or join my [Discord](https://discord.shaybox.com)
